const seeds = [
['Alertness','What should you do if you feel sleepy while driving?',['Open a window and continue','Stop somewhere safe and rest','Drive faster to arrive sooner','Use the horn regularly'],1,'Tiredness reduces concentration and reaction time. Stop in a safe place and rest before continuing.'],
['Alertness','What should you do before making a U-turn?',['Check all around for other road users','Signal only after turning','Use the pavement if traffic is busy','Flash your headlights'],0,'Check mirrors and blind spots and make sure the manoeuvre can be completed safely.'],
['Alertness','Why should you avoid distractions while driving?',['They increase fuel use only','They reduce your ability to observe and react','They make tyres wear faster','They affect road tax'],1,'Distractions take attention away from the road and can delay your response to hazards.'],
['Alertness','When should you use your mirrors?',['Only before parking','Before changing speed or direction','Only on motorways','Only when another driver sounds a horn'],1,'Use mirrors before changing speed or direction so you know how your actions may affect others.'],
['Alertness','What should you do when approaching a hidden junction?',['Speed up','Be ready for emerging traffic','Drive in the centre of the road','Sound the horn continuously'],1,'A hidden junction may conceal vehicles, cyclists or pedestrians, so reduce risk and be prepared to react.'],
['Attitude','A driver is following you too closely. What is the safest response?',['Brake sharply','Increase the gap in front of you','Speed up above the limit','Wave them past immediately'],1,'A larger gap ahead gives you more room to slow gradually and reduces the chance of a sudden stop.'],
['Attitude','Another driver makes a mistake. What should you do?',['Stay calm and give them space','Sound your horn in anger','Follow them closely','Block them from changing lane'],0,'Calm, considerate driving reduces conflict and helps everyone stay safe.'],
['Attitude','When should you flash your headlights?',['To show annoyance','To let others know you are there','To tell another driver to go','To thank someone'],1,'The Highway Code says flashing headlights should only be used to let other road users know you are there.'],
['Attitude','Why should you give extra room to cyclists in strong winds?',['They may be blown off course','They always travel faster','They cannot use brakes','They must ride on the pavement'],0,'Strong winds can make cyclists wobble or change position unexpectedly.'],
['Attitude','What should you do if an aggressive driver is behind you?',['Compete with them','Stay calm and avoid confrontation','Brake-test them','Prevent them overtaking'],1,'Avoid escalating the situation. Keep calm, drive predictably and allow space.'],
['Safety and your vehicle','What is the legal minimum tyre tread depth for most cars across the central three-quarters of the tread?',['1.0 mm','1.6 mm','2.5 mm','3.0 mm'],1,'For most cars the legal minimum is 1.6 mm across the central three-quarters of the breadth and around the entire circumference.'],
['Safety and your vehicle','Why should tyre pressures be checked regularly?',['To keep the horn louder','For safe handling and efficient tyre use','To improve radio reception','To reduce road tax'],1,'Correct tyre pressures support safe handling, braking, tyre life and efficiency.'],
['Safety and your vehicle','When should you check engine oil?',['Only before an MOT','Regularly, with the vehicle safely positioned','Only after a warning light stays on for a week','Never on a modern car'],1,'Regular fluid checks help prevent breakdowns and mechanical damage. Follow the vehicle handbook.'],
['Safety and your vehicle','A red brake warning light stays on while driving. What should you do?',['Ignore it until the next service','Stop safely and investigate/get help','Drive faster','Turn the radio off'],1,'A brake warning can indicate a serious safety problem. Stop safely and seek appropriate help.'],
['Safety and your vehicle','Why must windscreens and mirrors be kept clean?',['To improve visibility','To increase engine power','To lower insurance automatically','To make tyres last longer'],0,'Clear windows and mirrors are essential for seeing hazards and other road users.'],
['Safety margins','In dry conditions, what minimum time gap should you normally keep behind the vehicle ahead?',['One second','Two seconds','Four seconds','Ten seconds'],1,'Use at least a two-second gap in normal dry conditions, increasing it when conditions are worse.'],
['Safety margins','What should happen to your following distance on wet roads?',['It should be at least doubled','It should be halved','It should stay exactly the same','It only matters at night'],0,'Wet roads increase stopping distance, so leave at least twice the normal gap.'],
['Safety margins','Why should you slow down before a bend?',['You may not be able to see hazards beyond it','It saves road tax','It makes headlights brighter','It stops other cars overtaking'],0,'Your view may be restricted and you need to be able to stop within the distance you can see to be clear.'],
['Safety margins','What is most likely to increase stopping distance?',['A wet or icy road','A clean windscreen','Correct tyre pressure','Using dipped headlights'],0,'Low-grip surfaces reduce braking effectiveness and increase stopping distance.'],
['Safety margins','Why leave extra space behind a large vehicle on an uphill road?',['It may roll back','It cannot indicate','It has no mirrors','It must stop at every junction'],0,'A large vehicle may roll back slightly when moving off, so leave enough space.'],
['Hazard awareness','You see a ball roll into the road. What should you expect?',['A child may follow it','The road is closed','Traffic lights will change','A bus is approaching'],0,'A child may run after a ball without checking for traffic. Slow down and be ready to stop.'],
['Hazard awareness','Parked cars are blocking your view of the pavement. What should you do?',['Speed up','Slow down and look for pedestrians','Drive close to the parked cars','Use full beam'],1,'People may step out from between parked vehicles, so reduce speed and be prepared to stop.'],
['Hazard awareness','Why is a motorcyclist harder to judge at a junction?',['Their speed and distance can be difficult to assess','They always have priority','They cannot turn right','Their lights are illegal in daytime'],0,'Motorcycles are smaller and can be harder to see and judge accurately. Take extra time before emerging.'],
['Hazard awareness','What should you do when sunlight suddenly dazzles you?',['Speed up to leave the area','Slow down and, if necessary, stop safely','Close both eyes briefly','Use the horn'],1,'If glare reduces your view, reduce speed and stop safely if you cannot see properly.'],
['Hazard awareness','You approach a pedestrian crossing with people waiting. What should you do?',['Be prepared to slow or stop','Accelerate before they step out','Overtake the vehicle ahead','Sound the horn'],0,'Approach crossings carefully and be ready to give way or stop as required.'],
['Vulnerable road users','How much room should you give a cyclist when overtaking at up to 30 mph where possible?',['At least 0.5 m','At least 1.5 m','Exactly 1 m','No gap is required'],1,'The Highway Code advises at least 1.5 metres when overtaking cyclists at speeds up to 30 mph, with more space at higher speeds.'],
['Vulnerable road users','Why should you take extra care near schools?',['Children may act unpredictably','School roads have no speed limits','Children always have priority everywhere','Cars cannot brake near schools'],0,'Children may not judge traffic speed or distance well and may enter the road unexpectedly.'],
['Vulnerable road users','You are passing a horse rider. What should you do?',['Pass slowly and give plenty of room','Rev the engine','Sound the horn','Pass as closely as possible'],0,'Pass horses slowly, quietly and with plenty of space to avoid frightening them.'],
['Vulnerable road users','Why should you check for cyclists before opening a car door?',['A cyclist may be passing alongside','Cyclists must stop behind parked cars','It improves fuel economy','It changes your insurance'],0,'Opening a door into a cyclist’s path can cause serious injury. Check mirrors and blind spots first.'],
['Vulnerable road users','An older pedestrian is crossing slowly. What should you do?',['Be patient and allow them time','Sound the horn','Drive around them on the pavement','Move closer to hurry them'],0,'Give vulnerable pedestrians enough time and space to cross safely.'],
['Vehicle handling','What is the main risk of braking hard on ice?',['Loss of control','Higher fuel level','Brighter brake lights','Engine overheating'],0,'Harsh braking on a slippery surface can cause skidding and loss of steering control.'],
['Vehicle handling','What should you do before driving through flood water?',['Assess the depth and avoid it if unsafe','Accelerate hard into it','Switch the engine off while moving','Follow the car ahead closely'],0,'Flood water can be deeper or faster-moving than it appears and can damage or disable a vehicle.'],
['Vehicle handling','What can happen if you accelerate harshly on a slippery road?',['The driven wheels may lose grip','The tyres become wider','The brakes become stronger','The steering locks automatically'],0,'Harsh acceleration can break tyre grip, causing wheelspin or loss of control.'],
['Vehicle handling','Why should you use a lower gear on a steep downhill gradient?',['To help control speed with engine braking','To increase stopping distance','To switch off ABS','To use more fuel'],0,'A suitable lower gear can help control speed and reduce excessive reliance on the brakes.'],
['Vehicle handling','What should you do if your vehicle begins to aquaplane?',['Ease off the accelerator and avoid sudden inputs','Brake as hard as possible','Turn sharply','Accelerate'],0,'Smoothly easing off allows the tyres to regain contact and grip; sudden braking or steering can worsen the loss of control.'],
['Motorway rules','What colour are the reflective studs between a motorway carriageway and the hard shoulder?',['Red','Green','Blue','White'],0,'Red studs mark the left edge between the carriageway and hard shoulder.'],
['Motorway rules','What should you do if you miss your motorway exit?',['Continue to the next exit','Reverse on the hard shoulder','Make a U-turn','Stop in a live lane'],0,'Never reverse or turn around on a motorway. Continue safely to the next exit.'],
['Motorway rules','When may you use the hard shoulder as a running lane?',['Only when signs show it is open for traffic','Whenever traffic is slow','When overtaking','At night only'],0,'Use a hard shoulder as a traffic lane only where the road management signs specifically permit it.'],
['Motorway rules','A red X is displayed above your motorway lane. What does it mean?',['The lane is closed','The lane is for overtaking','Minimum speed applies','Parking is allowed'],0,'A red X means the lane is closed. You must move to an open lane when safe.'],
['Motorway rules','What should you do before joining a motorway from a slip road?',['Use the slip road to match traffic speed and find a safe gap','Stop at the end regardless of traffic','Drive directly into lane two','Use the hard shoulder'],0,'Use the acceleration lane to build an appropriate speed and merge safely without forcing other traffic to change course.'],
['Rules of the road','At a STOP sign, what must you do?',['Stop behind the line and check before proceeding','Slow only if traffic is visible','Sound the horn and continue','Stop only at night'],0,'STOP signs require you to stop at the line before proceeding when it is safe.'],
['Rules of the road','What does a solid white line along the centre of the road nearest you generally mean?',['You must not cross or straddle it except in limited permitted circumstances','You may always overtake','Parking is compulsory','The road is one-way'],0,'Solid white-line systems restrict crossing or straddling, subject to specific exceptions in the Highway Code.'],
['Rules of the road','When traffic lights change to amber, what should you normally do?',['Stop unless you have already crossed the line or stopping could cause an accident','Accelerate through every time','Reverse','Sound your horn'],0,'Amber means stop at the line unless you have already crossed it or are so close that stopping might cause a collision.'],
['Rules of the road','At an uncontrolled crossroads, what should you do?',['Approach carefully and be prepared to give way','Assume you have priority','Accelerate across','Only look right'],0,'Where priority is not marked, approach cautiously and do not assume other traffic will give way.'],
['Rules of the road','When should you enter a box junction?',['When your exit is clear, except when waiting to turn right in permitted circumstances','Whenever the light is green','When following a bus','Whenever traffic behind is impatient'],0,'Do not enter a box junction unless your exit is clear, apart from the specific right-turn exception.'],
['Road signs','What shape is a standard warning sign in the UK?',['Triangle','Circle','Rectangle only','Octagon'],0,'Most warning signs are triangular with a red border.'],
['Road signs','What shape is the STOP sign?',['Octagon','Triangle','Circle','Square'],0,'The STOP sign is octagonal so it can be recognised even when partly obscured.'],
['Road signs','What do circular signs with red borders usually give?',['Orders or prohibitions','Tourist information only','Motorway distances only','Parking prices only'],0,'Red-bordered circular signs generally tell you what you must not do or impose a restriction.'],
['Road signs','What do blue circular signs usually indicate?',['A positive instruction','A warning only','A road works diversion only','A parking fine'],0,'Blue circles generally give mandatory positive instructions, such as a direction to proceed.'],
['Road signs','What does an inverted red-bordered triangle mean?',['Give Way','No entry','Stop','National speed limit'],0,'The inverted triangle is the distinctive Give Way sign.'],
['Essential documents','What document shows the registered keeper of a vehicle?',['V5C registration certificate','MOT test receipt only','Driving licence counterpart','Insurance renewal notice'],0,'The V5C records the registered keeper and vehicle details; it is not proof of ownership.'],
['Essential documents','What must a vehicle normally have to be used on a public road?',['Valid insurance and any required tax and MOT','A service history only','A spare key','A dealership warranty'],0,'Road use normally requires the vehicle to meet legal insurance, tax and MOT requirements where applicable.'],
['Essential documents','What is an MOT mainly intended to check?',['Minimum roadworthiness and environmental standards at the time of test','Who owns the vehicle','Insurance price','Fuel cost'],0,'An MOT checks specified safety and environmental standards; it is not a guarantee of future condition.'],
['Essential documents','Who is responsible for ensuring a vehicle used on the road is properly insured?',['The person using it must ensure appropriate cover applies','The MOT tester','The fuel station','The previous keeper'],0,'A driver must make sure appropriate insurance cover applies before using the vehicle.'],
['Essential documents','What should you do when you change address on your driving licence?',['Tell DVLA and update your details','Wait until the licence expires','Only tell your insurer','Do nothing'],0,'Keep your driving-licence details up to date with DVLA.'],
['Incidents and emergencies','You are first at a collision. What should be your first priority?',['Protect the scene and prevent further danger','Move injured people immediately in every case','Take photographs before doing anything','Leave quickly'],0,'Make the area as safe as reasonably possible and avoid creating further danger before helping.'],
['Incidents and emergencies','When should you move an injured person after a collision?',['Only when necessary to avoid immediate danger or when appropriately directed','Always immediately','To make traffic move faster','Before calling emergency services'],0,'Unnecessary movement can worsen injuries. Move someone only if there is immediate danger or appropriate guidance.'],
['Incidents and emergencies','What information is useful when calling emergency services after a collision?',['Location, number of casualties and hazards','Your favourite route','The vehicle radio station','Your fuel receipt'],0,'Clear information about location, casualties and hazards helps emergency services respond effectively.'],
['Incidents and emergencies','A vehicle catches fire in a tunnel. What should you do if possible?',['Follow tunnel instructions, leave the vehicle safely and move away from danger','Stay inside with windows open','Reverse at speed','Block emergency access'],0,'Follow signs and emergency instructions, get people to safety and contact emergency services.'],
['Incidents and emergencies','Why should you switch off your engine after a serious collision when safe to do so?',['To reduce fire and other risks','To reset the radio','To cancel insurance','To cool the tyres'],0,'Switching off the engine can reduce risks such as fire and unintended vehicle movement.'],
['Vehicle loading','Why must a load be secured?',['To prevent it moving or falling and affecting control','To increase speed','To improve radio reception','To avoid using mirrors'],0,'An unsecured load can shift, affect handling or fall into the road and endanger others.'],
['Vehicle loading','What effect can a heavy roof load have?',['It can reduce stability, especially when cornering','It lowers the centre of gravity','It shortens the vehicle','It improves braking'],0,'Weight high on the vehicle raises its centre of gravity and can make it less stable.'],
['Vehicle loading','Before towing a trailer, what should you check?',['The towing limits and that the trailer/load are secure','Only the radio','Only the paint colour','That the boot is empty'],0,'The vehicle and trailer must be suitable, within permitted limits and correctly connected and loaded.'],
['Vehicle loading','Where should heavy luggage normally be placed?',['Low down and securely positioned','Loose on the parcel shelf','On the dashboard','Against the rear window'],0,'Keeping heavy items low and secure reduces movement and helps vehicle stability.'],
['Vehicle loading','Why should you avoid overloading a vehicle?',['It can affect steering, braking and stability','It makes headlights illegal automatically','It changes the registration number','It disables the horn'],0,'Excess weight can seriously affect vehicle handling and braking and may exceed legal limits.'],
['Other types of vehicle','Why should you leave extra space behind a large lorry?',['It improves your view and gives more stopping room','It makes the lorry go faster','It lets you use its slipstream','Lorries have no brake lights'],0,'Following too closely behind a large vehicle blocks your view and reduces your safety margin.'],
['Other types of vehicle','Why should you avoid cutting in closely after overtaking a lorry?',['The lorry needs a large stopping distance and you may enter its safety gap','Lorries cannot slow down','It is always illegal to overtake','The driver cannot see forward'],0,'Large vehicles need more room to stop. Do not remove the safety gap in front of them.'],
['Other types of vehicle','A bus is signalling to move away from a stop. What should you do when safe?',['Give it priority where possible','Accelerate past regardless','Sound your horn','Block it from moving'],0,'Allow buses, coaches and trams to move off when it is safe to do so, especially in built-up areas.'],
['Other types of vehicle','Why can long vehicles need extra room at junctions?',['They may swing out to complete a turn','They cannot indicate','They have priority over everyone','Their brakes only work straight ahead'],0,'Long vehicles may need to use more road space and can swing in the opposite direction before turning.'],
['Other types of vehicle','What should you remember when passing a tram?',['Follow local signs and avoid obstructing its path','Trams can steer around you','You may park on the tracks briefly','Trams always stop instantly'],0,'Trams run on fixed tracks and cannot steer around obstructions, so obey signs and keep their route clear.']
];

const variants = [
  q => q,
  q => `During an everyday drive, ${q.charAt(0).toLowerCase()+q.slice(1)}`,
  q => `You are preparing for a safe journey. ${q}`,
  q => `Think about the Highway Code. ${q}`,
  q => `In this situation, ${q.charAt(0).toLowerCase()+q.slice(1)}`,
  q => `For safe UK driving, ${q.charAt(0).toLowerCase()+q.slice(1)}`,
  q => `While driving responsibly, ${q.charAt(0).toLowerCase()+q.slice(1)}`,
  q => `On a normal UK road, ${q.charAt(0).toLowerCase()+q.slice(1)}`,
  q => `A learner driver asks: ${q}`,
  q => `Choose the safest answer. ${q}`
];

export const theoryQuestions = Array.from({length:700}, (_,i) => {
  const s = seeds[i % seeds.length];
  const round = Math.floor(i / seeds.length);
  const v = variants[round % variants.length];
  const options = [...s[2]];
  // Deterministic rotation makes answer positions vary while preserving correctness.
  const shift = (i * 3 + round) % options.length;
  const rotated = options.slice(shift).concat(options.slice(0,shift));
  const correctText = options[s[3]];
  return {
    id: i + 1,
    category: s[0],
    question: v(s[1]),
    options: rotated,
    correct: rotated.indexOf(correctText),
    explanation: s[4],
    visual: s[0].toLowerCase().replace(/[^a-z0-9]+/g,'-')
  };
});
